#!/usr/bin/env python
import random
import rospy
from std_msgs.msg import Bool

publisher = None
publish_target_timestamp = None


def updatePublishTargetTimestamp(current_timestamp):
    global publish_target_timestamp

    duration = random.uniform(1, 3)
    publish_target_timestamp = current_timestamp + rospy.Duration.from_sec(duration)


def onTimerEvent(event):
    if publisher is None:
        return None

    if publish_target_timestamp is None:
        updatePublishTargetTimestamp(event.current_real)

    if event.current_real >= publish_target_timestamp:
        publisher.publish(True)
        updatePublishTargetTimestamp(event.current_real)


if __name__ == "__main__":
    rospy.init_node("reset_publisher")
    publisher = rospy.Publisher("reset", Bool, queue_size=16)

    rospy.Timer(rospy.Duration.from_sec(0.01), onTimerEvent)
    rospy.spin()
